2025-03-26 09:47:42,787 : INFO : root : Loading config.
2025-03-26 09:47:42,789 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-03-26 09:47:42,789 : INFO : ConfigProcessor : Loading config from cache: /tmp/9121053a167b3a0609222a4623987891.mpf_cache
2025-03-26 09:47:42,823 : INFO : ConfigProcessor : Loading config from cache: /tmp/66ef204c87633dc02ca3efd475778ed9.mpf_cache
2025-03-26 09:47:42,823 : INFO : ConfigProcessor : Loading config from cache: /tmp/74f2825223a7abe8c76a0d15a1753cf2.mpf_cache
2025-03-26 09:47:42,823 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev7
2025-03-26 09:47:42,823 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2025-03-26-09-47-42-mpf-pinpi.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': '/home/pinpi/toedragons-pinball/logs/2025-03-26-09-47-42-mpf-pinpi.log'}
2025-03-26 09:47:42,823 : INFO : Machine : MPF path: /home/pinpi/pinpi/lib/python3.11/site-packages/mpf
2025-03-26 09:47:42,824 : INFO : Machine : Machine path: /home/pinpi/toedragons-pinball
2025-03-26 09:47:42,824 : INFO : Machine : Platform: linux
2025-03-26 09:47:42,824 : INFO : Machine : Python executable location: /home/pinpi/pinpi/bin/python
2025-03-26 09:47:42,824 : INFO : Machine : Python version: 3.11.2 (64-bit)
2025-03-26 09:47:42,824 : INFO : Machine : Initializing MPF...
2025-03-26 09:47:42,866 : INFO : FAST [NET] : Trying to connect to /dev/ttyAMA2 at 921600bps
2025-03-26 09:47:42,867 : INFO : FAST [NET] : Connected to /dev/ttyAMA2 at 921600bps
2025-03-26 09:47:42,869 : WARNING : FAST [NET] : Received XX response:F
2025-03-26 09:48:14,935 : INFO : Machine : Starting the main run loop with active modes: []
2025-03-26 09:48:14,935 : ERROR : root : 'attract'
Traceback (most recent call last):
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/commands/game.py", line 229, in __init__
    self.machine.run()
  File "/home/pinpi/pinpi/lib/python3.11/site-packages/mpf/core/machine.py", line 701, in run
    if not self.modes['attract'] in self.mode_controller.active_modes:
           ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'attract'
